run:
  timeout: 10m
  modules-download-mode: vendor
  skip-dirs-use-default: true

linters:
  enable:
    - errcheck
    - ineffassign
    - gocyclo
    - gofmt
    - gofumpt

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0

gocyclo:
  min-complexity: 15
